@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteStudentCommand" as DeleteStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":ArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete \nid/e0123456")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete \nid/e0123456")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse("id/e0123456")
activate DeleteCommandParser

DeleteCommandParser -> ArgumentTokenizer: tokenize("id/e0123456", "id/", "ev/")
activate ArgumentTokenizer

ArgumentTokenizer --> DeleteCommandParser: argMultiMap
deactivate ArgumentTokenizer

DeleteCommandParser -> ParserUtil:parseStudentId(argMultiMap.getValue("id/"))
activate ParserUtil

ParserUtil --> DeleteCommandParser: e0123456
deactivate ParserUtil

create DeleteStudentCommand
DeleteCommandParser -> DeleteStudentCommand : e0123456
activate DeleteStudentCommand

DeleteStudentCommand --> DeleteCommandParser : d
deactivate DeleteStudentCommand

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteStudentCommand : execute()
activate DeleteStudentCommand

DeleteStudentCommand -> Model : getStudent(e0123456)
activate Model

Model --> DeleteStudentCommand : toDelete
deactivate Model

DeleteStudentCommand -> Model : deleteStudent(toDelete)
activate Model

Model --> DeleteStudentCommand
deactivate Model

create CommandResult
DeleteStudentCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteStudentCommand : result
deactivate CommandResult

DeleteStudentCommand --> LogicManager : result
deactivate DeleteStudentCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteStudentCommand -[hidden]-> LogicManager
destroy DeleteStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml
