@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueStudentList
Class Student
Class Email
Class Major
Class Name
Class Phone
Class StudentId
Class Year
Class EnrolledEvents

Class UniqueEventList
Class Event
Class EventDate
Class EventTime
Class EventName
Class Participant
Class Blacklist

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Email
Student *--> Major
Student *--> Name
Student *--> Phone
Student *--> StudentId
Student *--> Year
Student --> "*" EnrolledEvents

AddressBook *--> "1" UniqueEventList
UniqueEventList --> "*" Event
Event *--> EventDate
Event *--> EventTime
Event *--> EventName
Event *--> Blacklist
Event --> "*" Participant


ModelManager -->"~* filtered" Student
ModelManager -->"~* filtered" Event
@enduml
